trigger:
  branches:
    include:
      - Dev

stages:
  - stage: Build
    displayName: 'Build and push stage'
    jobs:
      - job: Build
        displayName: 'Build and Push'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              repository: 'lmtmpp-parserapp'
              dockerfile: 'Dockerfile'
              containerRegistry: 'turingACR'
              tags: latest
              arguments: '--no-cache'
              
  - stage: Deploy
    displayName: 'Deploy to App Service'
    jobs:
    - job: Deploy
      displayName: Deploy to App Service
      steps:
      - task: AzureWebAppContainer@1
        inputs:
         ConnectionType: 'AzureRM'
         azureSubscription: 'LMT-PRODUCTS'   
         AppName: 'lmtmpp-parserapp'
         containers: 'turing.azurecr.io/lmtmpp-parserapp:latest'
 